### ISSUE TITLE
feature request: make `reboot` on rescue shell work

### ISSUE THREAD

**Issue by DrMcCoy** [slashbeast/better-initramfs#59]
It would be great if `reboot` on the rescue shell worked, so I can, for example, reboot a failed boot attempt remotely, where I can't physically type ctrl-alt-del.

Right now, typing `reboot` fails with:

```
reboot: can't execute '/sbin/telinit': No such file or directory
```

I assume this is known, hence the message to press ctrl-alt-del?

**Comment by slashbeast** [comment]
This is not easy to solve in an elegant way. the PID 1 is /bin/sh from busybox, since we need to do both switch_root and then exec the real /sbin/init so we need to have it as PID 1, however then it have no smarts to handle reboot or shutdown. I am not fond of writing my own init and rather not have sysvinit there. The sensible middle ground would be to utilize kernel's CONFIG_MAGIC_SYSRQ=y and then have the `reboot` as a shell script that literally does `echo b >/proc/sysrq-trigger`, same for poweroff. Perhaps with information for user what is happening in case kernel lacks sysrq support.

**Comment by DrMcCoy** [comment]
Ah, I see, thanks for the explanation.

**Comment by slashbeast** [comment]
This is now addressed in devel branch.

**Comment by DrMcCoy** [comment]
Oh, nice, that works, thanks! :)

Of course, when I'm doing that from remote, the ssh session hangs, because the reboot/shutdown doesn't close the ssh session properly.

Doing this:
```
        nohup sh -c "sleep 1; echo 'b' >/proc/sysrq-trigger" &
        killall dropbear
```

seems to work well around it, but it's a bit hacky. The nohup is necessary because otherwise, terminating dropbear terminates its sh session right then and there. Dunno if there's a nicer way to achieve that.

**Comment by slashbeast** [comment]
That bring to the table whole service management or hacky sync on sleep to hope that the process managed to close the connections in time.

I consider it a non-issue since you can deal with it client side.

Click `enter` then `~` and then `.` and the frozen SSH client will exit client side.

**Comment by DrMcCoy** [comment]
Okay
